# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
sudo: required
dist: trusty
script: make
os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
compiler:
  - gcc
  - clang
